### PR TITLE
DAOS-2240 Build RPMs

### PR DESCRIPTION
**Pull request by brianjmurrell**

### CODE REVIEW

**Comment by liw** [comment]
Since we link libraft statically into librdb, why do we need RPMs?

**Comment by brianjmurrell** [comment]
> Since we link libraft statically into librdb, why do we need RPMs?

Even though we link to the static library, something has to provide it to be linked with at build time.  *raft-devel* does that.

This is necessary because *raft* is not part of the doas repository but rather it is just linked to it as a submodule and so when daos releases are made, the raft project will not part of those releases.  The *raft-devel* library then provides the static library that daos releases can use at build time.

If we want our raft to be included in daos releases and be built with daos, then it needs to be imported into the daos project and maintained along with it.  Doing so of course will also increase the build time of daos which might be an unnecessary penalty if raft ends up not changing very much.

**Comment by liw** [comment]
> Even though we link to the static library, something has to provide it to be linked with at build time. _raft-devel_ does that.

Currently, after initializing the submodule, we treat src/rdb/raft simply as a part of DAOS source. And, we currently don't need a raft-devel.

> This is necessary because _raft_ is not part of the doas repository but rather it is just linked to it as a submodule and so when daos releases are made, the raft project will not part of those releases. The _raft-devel_ library then provides the static library that daos releases can use at build time.

I implemented this submodule. What puzzles me is why changes are _needed_.

What does "release" mean? If it means making a DAOS tarball or SRPM, can we include raft code?

> If we want our raft to be included in daos releases and be built with daos, then it needs to be imported into the daos project and maintained along with it. Doing so of course will also increase the build time of daos which might be an unnecessary penalty if raft ends up not changing very much.

Again, it puzzles me why "it needs to be imported into the daos project". Could you elaborate a bit, please?

**Comment by brianjmurrell** [comment]
> Currently, after initializing the submodule, we treat src/rdb/raft simply as a part of DAOS source. And, we currently don't need a raft-devel.

That's fine for source-level builds done by developers from git.  But that's not how software is _released_ and packaged in the Linux ecosystem.  That is done through formal releases, usually as tarballs, etc.

Current DAOS releases can be found [here](https://github.com/daos-stack/daos/releases) for example.

If you download a [tarball of the latest release](https://github.com/daos-stack/daos/archive/v0.4.tar.gz) and look in the daos-0.4/src/rdb/raft directory of it you will see that it's empty.  That's because GitHub doesn't (and shouldn't) include the contents of submodules in a software release.

> I implemented this submodule. What puzzles me is why changes are _needed_.

Changes are needed to support the notion that submodules indicate a delineation between projects and those separate projects need their own releases and packages.

> What does "release" mean? If it means making a DAOS tarball

Yes.
> or SRPM, can we include raft code?

an SRPM can reflect a release, but it is typically not considered release collateral the way the tarball is.

> Again, it puzzles me why "it needs to be imported into the daos project".

It really doesn't need to be and my gut feeling is that it shouldn't be as it's a separate library that has a different, probably slower change cadence than DOAS.  I wasn't actually endorsing that it should be imported, but merely just suggesting what would need to be done if we wanted our raft to be included in the DAOS release rather than it having it's own releases which DAOS requires at build time.

**Comment by liw** [comment]
The behavior of "releases" you linked to is specific to GitHub + submodules, isn't it? Some quick searches reveal that this can be worked around. See https://github.com/cockroachdb/cockroach/tree/master/c-deps for example. They use submodules extensively, and their GitHub release tarballs include the submodule source. See also https://github.com/micropython/micropython/releases for another example. They seem to adopt a simpler workflow---just upload their own tarballs, which includes the submodule source. I think we need our own scons build target for generating tarballs anyway.

**Comment by brianjmurrell** [comment]
> See https://github.com/cockroachdb/cockroach/tree/master/c-deps for example

`vendor/` (submodule) subdir in the [v19.1.0-rc.2.tar.gz](https://github.com/cockroachdb/cockroach/archive/v19.1.0-rc.2.tar.gz) is empty.  So confusing at least.

I didn't hunt long enough through the micropython project to find the submodules to compare to their release tarballs, but I suspect it's the same.

So sure, there are workarounds, but they all make the release process more cumbersome and error-prone and make using them in CI more difficult.

@liw Can I ask why you are resistant to doing this in (what is IMHO) the most straightforward manner and just creating a package for every separate project?  The resulting product built from a raft-devel will be no different than if we write up some error-prone release process to try to include the submodule in the daos release.  Trying to do that for every PR is also going to add more moving parts to the CI process which means more opportunity for breakage on PRs, slowing down development.

**Comment by liw** [comment]
> `vendor/` (submodule) subdir in the [v19.1.0-rc.2.tar.gz](https://github.com/cockroachdb/cockroach/archive/v19.1.0-rc.2.tar.gz) is empty. So confusing at least.

I guess `vendor` is left out intentionally, as its contents are copies of other projects.

> I didn't hunt long enough through the micropython project to find the submodules to compare to their release tarballs, but I suspect it's the same.
> 
> So sure, there are workarounds, but they all make the release process more cumbersome and error-prone and make using them in CI more difficult.

The confusion comes from GitHub's specific implementation of "releases", I think.

> @liw Can I ask why you are resistant to doing this in (what is IMHO) the most straightforward manner and just creating a package for every separate project? The resulting product built from a raft-devel will be no different than if we write up some error-prone release process to try to include the submodule in the daos release. Trying to do that for every PR is also going to add more moving parts to the CI process which means more opportunity for breakage on PRs, slowing down development.

To me, we treat raft as part of daos, with the dependency reliably defined by submoduling. This is the most straightforward way of understanding how we can reliably reproduce the same build from a particular "release". If we were to treat it as a separate project, then we need to care about how to link reliably from a daos "release" to a precise raft RPM. And this seems to require bumping some raft version each time daos needs to update its raft dependency. To me, these are conceptual complexities.

Hence, I'm interested in the possibility of avoiding this 218 lines of new code.

**Comment by jolivier23** [comment]
@brianjmurrell @liw Perhaps it would be good for you guys to chat for a few minutes to get on the same page?

**Comment by liw** [comment]
@jolivier23, Brian and I chatted about this. I think we have an understanding of the backgrounds and the implications. I'm fine to try the new approach. Will check this PR again tomorrow morning.

**Pull request merged**
