### PR TITLE
DAOS-14443 server: Honor lease when campaigning

### PR DESCRIPTION
**Pull request by liw**
As a safety measure, raft_election_start should return an error if there might be a valid lease to another replica. This patch extracts such as lease check into a common function and changes raft_election_start to return RAFT_ERR_MIGHT_VIOLATE_LEASE when the lease check is positive.

### CODE REVIEW

**Review by kccain — APPROVED** [review]

**Comment by liw** [comment]
Tested this with daos https://github.com/daos-stack/daos/pull/13180: No issue found.

**Review by brianjmurrell — COMMENTED** [review]
This should have included a `Version:`/`Release:` update.  We should never, ever land dependency updates with updating the version and/or release.

**Comment by liw** [comment]
@brianjmurrell, would you mind elaborating a bit on the reason, please? It would be inconvenient and strange to include packaging changes in _every_ landing.

**Comment by brianjmurrell** [comment]
> @brianjmurrell, would you mind elaborating a bit on the reason, please? It would be inconvenient and strange to include packaging changes in _every_ landing.

Because Artifactory can get confused when it has two copies of a package with the same version and release.

**Comment by liw** [comment]
> > @brianjmurrell, would you mind elaborating a bit on the reason, please? It would be inconvenient and strange to include packaging changes in _every_ landing.
> 
> Because Artifactory can get confused when it has two copies of a package with the same version and release.

Thanks, @brianjmurrell. The release part gets bumped regardless:

    master build 55 (#75): raft-devel-0.10.1-2.410.g48fd0f5.el8.x86_64.rpm # Landing commit of this PR
                                               ^^^^^^^^^^^^
    master build 54 (#74): raft-devel-0.10.1-2.409.gc354cd7.el8.x86_64.rpm
                                               ^^^^^^^^^^^^

Also, `daos` requires the exact `version-release` of `raft`. Are these really insufficient?

**Comment by brianjmurrell** [comment]
> Also, `daos` requires the exact `version-release` (e.g., `0.10.1-2.410.g48fd0f5`) of `raft`. Are these really insufficient?

This requirement has nothing to do with daos and it's packaging.  It has to do with the fragility of Artifactory.  But as you say, because we put the gitsha in the release, it does effectively get **changed** but it's not a _bump_ technically as the new one could be lexicographically inferior to the old one.

In any case, technically it's all good.  It's just not very good packaging process, IMO.  In the RPM packaging world, any code change should result in a version bump and any packaging change should result in a release bump.

**Comment by liw** [comment]
> > Also, `daos` requires the exact `version-release` (e.g., `0.10.1-2.410.g48fd0f5`) of `raft`. Are these really insufficient?
> 
> This requirement has nothing to do with daos and it's packaging. It has to do with the fragility of Artifactory. But as you say, because we put the gitsha in the release, it does effectively get **changed** but it's not a _bump_ technically as the new one could be lexicographically inferior to the old one.
> 
> In any case, technically it's all good. It's just not very good packaging process, IMO. In the RPM packaging world, any code change should result in a version bump and any packaging change should result in a release bump.

@brianjmurrell, not just the SHA, but also the `409` and `410` numbers.

**Comment by brianjmurrell** [comment]
Oh yes.  You are right.  I was mistaking that for the manual part of the `Release:` update.  But indeed it automatically determined as the number of commits since the last tag.

Although, IMO, my comments on good packaging practices stand as this particular change, being a code/functionality change of the software package, should involve a version to indicate the new behaviour (or bugfix if that's what it is).  You are of course free to disagree if you wish.  I'm just counselling based on my experience and expertise.

**Comment by liw** [comment]
@brianjmurrell, thanks.

I wouldn't say I disagree with the principle. My concern is in applying the principle to **every landing**. That would be quite an impact. Hence, I couldn't help asking myself: "Why other projects I have worked on or looked into do not require **every landing** to bump version-release? For instance,  `daos` does not, even though its packages go to Artifactory." That was why I decided to ask.

For `raft`, I'm fine with bumping version-release occasionally when we want to pick up a new `raft` commit in `daos` (and maybe to update the packaging code), as long as the major version stays at 0 to comply with semantic versioning.

**Pull request merged**
